### ISSUE TITLE
Will there be new builds in Releases?

### ISSUE THREAD

**Issue by Mesmer55** [nightmareci/HeborisC7EX-SDL2#32]
The current latest release is from 2021 and there have been commits since

**Comment by nightmareci** [comment]
We've been polishing it up since then, yes. And I do want to put up a new release, when I determine it's good and ready, which is not yet. For one, there's still some stuff I want to do to finish up the Vita port before the release; I'll be officially supporting a Vita port from this repo right alongside Windows/Mac/Linux, it will be kept completely up-to-date in sync with the desktop computer ports. The goal is to get it to a "finished product" status for the officially supported platforms, no longer partially broken, nor amateurish in functionality; it was not a "finished product" when I started.

I won't give you a time when it'll be ready, we're not on the clock here. If you want it sooner, ask me what needs doing and I'll tell you, then contribute the changes yourself.

**Comment by Mesmer55** [comment]
Thank you for the quick reply! Take all the time you need, for the best version of Heboris on the internet it's definitely worth it. Until then anyone can compile the latest commit themselves anyways.
